Repository NIFCLOUD-mbaas/ncmb_android, pull requests merged in 2018-04, with the labels that each got.

#152 (android) play-services全体でなく、必要なplay-services-gcmのみを指定
  ncmb-core/build.gradle
Labels: in progress

#102 update query count
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBQuery.java
Labels: 不具合

#122 fix #117 get method for NullPointerException
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBBase.java
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBBaseTest.java
Labels: Waiting For Review, 不具合

#112 fix wakelock release
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBDialogActivity.java
Labels: Waiting For Review, 不具合

#113 fixed response signature check
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBConnection.java
Labels: Waiting For Review

#92 add own fields when signup
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBUser.java
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBUserService.java
  ncmb-core/src/test/assets/yaml/mbaas.yml
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBUserTest.java
Labels: Enhancement

#154 NCMBServicePool の作りの対応
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMB.java
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBServicePool.java
Labels: in progress

#77 Fix/parse format error
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBBase.java
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBFile.java
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBInstallation.java
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMBInstallationService.java
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBBaseTest.java
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBInstallationServiceTest.java
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBObjectTest.java
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBUserServiceTest.java
Labels: Waiting For Review, 不具合

#158 Update version to 2.4.0 to Release prepare
  ncmb-core/src/main/java/com/nifty/cloud/mb/core/NCMB.java
  ncmb-core/src/test/assets/json/valid_get_installation_response.json
  ncmb-core/src/test/assets/json/valid_get_searchInstallation_response.json
  ncmb-core/src/test/assets/yaml/mbaas.yml
  ncmb-core/src/test/java/com/nifty/cloud/mb/core/NCMBInstallationServiceTest.java
Labels: in progress
